import React, { useState, useEffect } from 'react';
import { Star, ChevronLeft, ChevronRight } from 'lucide-react';

const Testimonials: React.FC = () => {
  const [currentIndex, setCurrentIndex] = useState(0);

  const testimonials = [
    {
      name: 'Sarah Chen',
      role: 'Content Marketing Manager',
      company: 'TechFlow',
      avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      rating: 5,
      quote: 'ContentCraft AI has revolutionized our content strategy. What used to take our team 8 hours now takes 30 minutes. The quality is consistently high across all platforms, and our engagement rates have increased by 40% since we started using it. It\'s like having an entire content team at your fingertips.'
    },
    {
      name: 'Marcus Rodriguez',
      role: 'Founder',
      company: 'GrowthHack Pro',
      avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      rating: 5,
      quote: 'As a solo entrepreneur, ContentCraft AI is like having an entire content team. The platform understands my brand voice perfectly and generates content that resonates with my audience. It\'s saved me countless hours and significantly improved my content quality. I can\'t imagine running my business without it.'
    },
    {
      name: 'Emily Watson',
      role: 'Social Media Director',
      company: 'BrandVibe Agency',
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      rating: 5,
      quote: 'Managing content for 15+ clients was overwhelming until we found ContentCraft AI. The platform\'s ability to maintain distinct brand voices while scaling content production has been a game-changer. Our clients love the consistency and quality, and we\'ve been able to take on 3x more clients.'
    },
    {
      name: 'David Kim',
      role: 'YouTube Creator',
      company: '500K Subscribers',
      avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      rating: 5,
      quote: 'The YouTube Shorts scripts generated by ContentCraft AI are incredible. They understand the hook-problem-solution format perfectly and create scripts that actually convert. My view duration has increased by 35% since I started using their scripts. It\'s a content creator\'s dream tool.'
    },
    {
      name: 'Lisa Thompson',
      role: 'Marketing Director',
      company: 'SaaS Startup',
      avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      rating: 5,
      quote: 'ContentCraft AI has transformed how we approach content marketing. The SEO blog posts are incredibly well-structured and optimized, while the social media content drives real engagement. We\'ve seen a 60% increase in organic traffic and our social media following has doubled in just 3 months.'
    }
  ];

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentIndex((prevIndex) => (prevIndex + 1) % testimonials.length);
    }, 6000);

    return () => clearInterval(timer);
  }, [testimonials.length]);

  const nextTestimonial = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % testimonials.length);
  };

  const prevTestimonial = () => {
    setCurrentIndex((prevIndex) => (prevIndex - 1 + testimonials.length) % testimonials.length);
  };

  return (
    <section className="py-24 bg-blue-50/30" data-aos="fade-up">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-semibold text-gray-900 mb-6">
            Loved by content creators worldwide
          </h2>
          <p className="text-xl text-gray-600 leading-relaxed">
            See what our customers say about their experience with ContentCraft AI
          </p>
        </div>

        <div className="relative">
          <div className="bg-white rounded-xl shadow-lg p-8 md:p-12">
            <div className="flex items-center justify-center mb-6">
              {[...Array(testimonials[currentIndex].rating)].map((_, i) => (
                <Star key={i} className="w-5 h-5 text-yellow-400 fill-current" />
              ))}
            </div>
            
            <blockquote className="text-lg text-gray-700 text-center mb-8 leading-relaxed">
              "{testimonials[currentIndex].quote}"
            </blockquote>
            
            <div className="flex items-center justify-center">
              <img
                src={testimonials[currentIndex].avatar}
                alt={testimonials[currentIndex].name}
                className="w-12 h-12 rounded-full mr-4"
                loading="lazy"
              />
              <div className="text-center">
                <div className="font-semibold text-gray-900">{testimonials[currentIndex].name}</div>
                <div className="text-gray-600 text-sm">
                  {testimonials[currentIndex].role} at {testimonials[currentIndex].company}
                </div>
              </div>
            </div>
          </div>

          {/* Navigation Buttons */}
          <button
            onClick={prevTestimonial}
            className="absolute left-0 top-1/2 transform -translate-y-1/2 -translate-x-4 bg-white rounded-xl shadow-lg p-3 hover:bg-gray-50 hover:shadow-xl hover:-translate-y-1/2 hover:-translate-x-5 transition-all duration-200"
            aria-label="Previous testimonial"
          >
            <ChevronLeft className="w-6 h-6 text-gray-600" />
          </button>
          
          <button
            onClick={nextTestimonial}
            className="absolute right-0 top-1/2 transform -translate-y-1/2 translate-x-4 bg-white rounded-xl shadow-lg p-3 hover:bg-gray-50 hover:shadow-xl hover:-translate-y-1/2 hover:translate-x-5 transition-all duration-200"
            aria-label="Next testimonial"
          >
            <ChevronRight className="w-6 h-6 text-gray-600" />
          </button>

          {/* Dots Indicator */}
          <div className="flex justify-center mt-8 space-x-2">
            {testimonials.map((_, index) => (
              <button
                key={index}
                onClick={() => setCurrentIndex(index)}
                className={`w-3 h-3 rounded-full transition-colors ${
                  index === currentIndex ? 'bg-teal-600' : 'bg-gray-300'
                }`}
                aria-label={`Go to testimonial ${index + 1}`}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Testimonials;